# ASI-Omega Audit Pipeline — Build .exe
# Compiles PowerShell scripts to standalone Windows executables.
#
# Usage:
#   pwsh build-exe.ps1
#
# Requires: PowerShell 7+ and internet access (for ps2exe module)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path

Write-Host ""
Write-Host "  ================================================" -ForegroundColor Cyan
Write-Host "    ASI-Omega Audit Pipeline — Build" -ForegroundColor Cyan
Write-Host "  ================================================" -ForegroundColor Cyan
Write-Host ""

# ─────────────────────────────────────────────────────
# 1. Check / install ps2exe
# ─────────────────────────────────────────────────────
$ps2exe = Get-Module -ListAvailable ps2exe
if(-not $ps2exe){
    Write-Host "  Installerer ps2exe-modulen..." -ForegroundColor White
    Install-Module ps2exe -Scope CurrentUser -Force -AllowClobber
    $ps2exe = Get-Module -ListAvailable ps2exe
    if(-not $ps2exe){
        Write-Host "  Kunne ikke installere ps2exe." -ForegroundColor Red
        Write-Host "  Proev manuelt: Install-Module ps2exe -Scope CurrentUser" -ForegroundColor Yellow
        exit 1
    }
    Write-Host "  [OK] ps2exe installert" -ForegroundColor Green
} else {
    Write-Host "  [OK] ps2exe allerede installert" -ForegroundColor Green
}

Import-Module ps2exe -Force

# ─────────────────────────────────────────────────────
# 2. Create dist/ folder
# ─────────────────────────────────────────────────────
$distDir = Join-Path $root 'dist'
if(-not (Test-Path $distDir)){
    New-Item -ItemType Directory -Force -Path $distDir | Out-Null
}

# ─────────────────────────────────────────────────────
# 3. Create wrapper scripts for exe compilation
# ─────────────────────────────────────────────────────
# ps2exe needs a self-contained script — we create thin wrappers
# that set $root and call the real scripts.

$cliWrapper = Join-Path $root 'dist\_cli_wrapper.ps1'
@"
# ASI-Omega Audit Pipeline — CLI Wrapper
# This file is auto-generated by build-exe.ps1
`$ErrorActionPreference = 'Stop'
`$root = Split-Path -Parent ([System.Diagnostics.Process]::GetCurrentProcess().MainModule.FileName)
`$auditScript = Join-Path `$root 'audit.ps1'

if(-not (Test-Path `$auditScript)){
    Write-Host ""
    Write-Host "  Finner ikke audit.ps1 i samme mappe som .exe-filen." -ForegroundColor Red
    Write-Host "  Pakk ut alle filene foer du kjoerer programmet." -ForegroundColor Yellow
    Write-Host ""
    Read-Host "  Trykk Enter for aa lukke"
    exit 1
}

# Forward all arguments to audit.ps1
pwsh -NoProfile -File `$auditScript @args
"@ | Set-Content -Encoding UTF8 -Path $cliWrapper

$guiWrapper = Join-Path $root 'dist\_gui_wrapper.ps1'
@"
# ASI-Omega Audit Pipeline — GUI Wrapper
# This file is auto-generated by build-exe.ps1
`$ErrorActionPreference = 'Stop'
`$root = Split-Path -Parent ([System.Diagnostics.Process]::GetCurrentProcess().MainModule.FileName)
`$guiScript = Join-Path `$root 'audit-gui.ps1'

if(-not (Test-Path `$guiScript)){
    Add-Type -AssemblyName System.Windows.Forms
    [System.Windows.Forms.MessageBox]::Show(
        "Finner ikke audit-gui.ps1 i samme mappe som .exe-filen.`nPakk ut alle filene foer du kjoerer programmet.",
        "ASI-Omega Audit Pipeline",
        "OK",
        "Error"
    )
    exit 1
}

pwsh -NoProfile -File `$guiScript
"@ | Set-Content -Encoding UTF8 -Path $guiWrapper

# ─────────────────────────────────────────────────────
# 4. Compile executables
# ─────────────────────────────────────────────────────
$builds = @(
    @{
        Name = "ASI-Omega-Audit.exe"
        Source = $cliWrapper
        Description = "ASI-Omega Audit Pipeline — Kryptografisk integritetskontroll"
        NoConsole = $false
    },
    @{
        Name = "ASI-Omega-Audit-GUI.exe"
        Source = $guiWrapper
        Description = "ASI-Omega Audit Pipeline — Grafisk brukergrensesnitt"
        NoConsole = $true
    }
)

$successCount = 0

foreach($b in $builds){
    $outPath = Join-Path $distDir $b.Name
    Write-Host "  Kompilerer $($b.Name)..." -ForegroundColor White

    try {
        $ps2exeArgs = @{
            inputFile  = $b.Source
            outputFile = $outPath
            title      = "ASI-Omega Audit Pipeline"
            description = $b.Description
            company    = "Shaho Nader"
            product    = "ASI-Omega Audit Pipeline"
            version    = "1.0.0"
            copyright  = "2024-2025 Shaho Nader"
        }
        if($b.NoConsole){
            $ps2exeArgs.noConsole = $true
        }

        Invoke-ps2exe @ps2exeArgs

        if(Test-Path $outPath){
            Write-Host "    [OK] $($b.Name)" -ForegroundColor Green
            $successCount++
        } else {
            Write-Host "    [!] Kompilering feilet" -ForegroundColor Yellow
        }
    } catch {
        Write-Host "    [!] Feil: $_" -ForegroundColor Yellow
    }
}

# ─────────────────────────────────────────────────────
# 5. Copy required files to dist/
# ─────────────────────────────────────────────────────
Write-Host ""
Write-Host "  Kopierer prosjektfiler til dist/..." -ForegroundColor White

$filesToCopy = @(
    'audit.ps1',
    'audit-gui.ps1',
    'install.ps1',
    'README.md',
    'LICENSE'
)
$dirsToCopy = @(
    'src',
    'tools',
    'sample',
    'docs',
    'tests'
)

foreach($f in $filesToCopy){
    $src = Join-Path $root $f
    if(Test-Path $src){
        Copy-Item -Force $src (Join-Path $distDir $f)
    }
}
foreach($d in $dirsToCopy){
    $src = Join-Path $root $d
    if(Test-Path $src){
        Copy-Item -Recurse -Force $src (Join-Path $distDir $d)
    }
}

# Clean up wrapper scripts
Remove-Item -Force $cliWrapper -ErrorAction SilentlyContinue
Remove-Item -Force $guiWrapper -ErrorAction SilentlyContinue

# ─────────────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────────────
Write-Host ""
Write-Host "  ================================================" -ForegroundColor Green
Write-Host "    BUILD FULLFORT" -ForegroundColor Green
Write-Host "  ================================================" -ForegroundColor Green
Write-Host ""
Write-Host "  $successCount .exe-fil(er) kompilert til:" -ForegroundColor White
Write-Host "    $distDir" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Innhold:" -ForegroundColor Yellow

$distFiles = Get-ChildItem -Path $distDir -File | Where-Object { $_.Name -notlike '_*' }
foreach($f in $distFiles){
    $sizeKB = [math]::Round($f.Length / 1KB, 1)
    Write-Host "    $($f.Name) ($sizeKB KB)" -ForegroundColor White
}

Write-Host ""
Write-Host "  For aa distribuere:" -ForegroundColor Yellow
Write-Host "    1. Zip hele dist/-mappen" -ForegroundColor White
Write-Host "    2. Send til brukere" -ForegroundColor White
Write-Host "    3. Brukere pakker ut og kjoerer .exe-filen" -ForegroundColor White
Write-Host ""
Write-Host "  MERK: Mottakere trenger PowerShell 7+ installert." -ForegroundColor Gray
Write-Host "        https://github.com/PowerShell/PowerShell/releases" -ForegroundColor Gray
Write-Host ""
